main: plugin.HungerGames
name: Zebiiii
version: 1.0
author: me
description: Un plugin de bg zeubi

commands:
  kit:
    description: Selectionne ton kit
    usage: /kit
    permission: Zebiiii.kitpermission

  surfacerandom:
    description: Go to the surface at a random X
    usage: /surfacerandom
    permission: Zebiiii.surfacerandompermission

  ez:
    description: gn all
    usage: /ez
    permission: Zebiiii.ezpermission

  fiou:
    description: Youhou des porcelets !
    usage: /fiou <number>
    permission: Zebiiii.fioupermission